### ISSUE TITLE
Use hls links instead of mp4 links for DataChats

### ISSUE THREAD

**Issue by filipsch** [datacamp/datachats-content#1]
I noticed that some DataChats only have mp4 links specified, like [this one](https://github.com/datacamp/datachats-content/blob/master/datachat28.yml). This format is suboptimal to the HLS version, as there is no way to select different qualities. Make sure to explicitly add those HLS links; the DataChats app nor the projector app will automagically figure them out for you.

**Comment by yashasroy** [comment]
@filipsch Our video editor uploads the raw MP4s into the [/interviews](https://s3.console.aws.amazon.com/s3/buckets/videos.datacamp.com/interviews/?region=us-east-1&tab=overview) folder on S3 (as Fernando did), which does not automatically transcode them, since they aren't uploaded to the [/raw](https://s3.console.aws.amazon.com/s3/buckets/videos.datacamp.com/raw/?region=us-east-1&tab=overview) folder the way course videos are. As a result, I don't have any HLS links for the DataChats.

Should the /interviews folder be migrated to /raw?

**Comment by filipsch** [comment]
@yashasroy there is an AWS lambda job that looks at the `/raw` folder, and converts the mp4 files there to HLS files. Copying the interviews folder over to raw should fix it, indeed. Don't move it; copy it; otherwise the current datachats videos might go bust.

Also, I didn't mention how urgent it is, because I'll leave it up to you to decide how much priority you want to give this. Just saying that the current way links are added give a poor experience with people in low bandwidth regions.

**Comment by yashasroy** [comment]
@filipsch I would do this immediately but I lack the requisite S3 credentials - I have read only permissions to the videos bucket.  Two options:

- Someone with the credentials does the copy and I'll update the links for all DataChats.
- You grant me the appropriate permissions and I handle it. 

The second point reminds me - I was wondering if this repository was intentionally public?

**Comment by filipsch** [comment]
@yashasroy It is. You can file a request in https://github.com/datacamp/devops for S3 credentials with enough rights; try to be as specific as possible and reference this issue. Thanks!
